### ISSUE TITLE
Feedback from testing

### ISSUE THREAD

**Issue by arogozhnikov** [GracefulTabby/streamlit-chunk-file-uploader#16]
Hi Ryuya, 

thanks for component, I've tested it after your post here https://github.com/streamlit/streamlit/issues/6999#issuecomment-1914735964

I've used connection to server via cludflare, that would not allow files >100MB, and I've used your default example for testing. Here are results:

- first file (170Mb) was uploaded, and downloaded successfully, I've checked md5 - it was all good
- second file (~350mb) - it reports successful upload, but the file is corrupted (I can confirm problem appears during an upload, as I've also computed hash on the server), problem is not in the beginning of file, but seemingly in the end. File size was correct.

I've also noticed there is minor inconsistency in the interface: if I delete file from uploaded (e.g. after an error), then try upload again - nothing happens. I need to reload the page to force the component accepting files again.

**Comment by arogozhnikov** [comment]
Also, if you find this helpful, this is how I generate files for testing:

```
import numpy as np
import pandas as pd
pd.DataFrame(np.random.RandomState(42).random([10_000, 3_000]).astype('float32')).to_parquet('~/Downloads/test_file.pqt')
```

**Comment by GracefulTabby** [comment]
@arogozhnikov 

Thanks for the review!
Immediately resolve problems with file checksums or the same file not being uploaded.

Thank you for providing the test file generation code.

**Comment by GracefulTabby** [comment]
@arogozhnikov

I would like to report that the problem has been resolved.
It was a very elementary mistake of rearranging the chunk numbers incorrectly.
This feature was tested using some large files and found to be ok.
Thank you for your valuable review.

**Comment by arogozhnikov** [comment]
Hey @GracefulTabby  
I can confirm it uploads big files correctly now!

**Comment by GracefulTabby** [comment]
Thank you for your contribution! 
Close the issue.
